<?php
$COLORS = [
	'black' => ['qcode' => 'black', 'cn' => '黑色', 'code' => '#000000'],
	'maroon' => ['qcode' => 'maroon', 'cn' => '粟色', 'code' => '#800000'],
	'darkred' => ['qcode' => 'darkred', 'cn' => '暗红色', 'code' => '#8B0000'],
	'brown' => ['qcode' => 'brown', 'cn' => '褐色', 'code' => '#A52A2A'],
	'firebrick' => ['qcode' => 'firebrick', 'cn' => '火砖色', 'code' => '#B22222'],
	'crimson' => ['qcode' => '', 'cn' => '暗深红色', 'code' => '#DC143C'],
	'red' => ['qcode' => 'red', 'cn' => '红色', 'code' => '#FF0000'],
	'orangered' => ['qcode' => '', 'cn' => '红橙色', 'code' => '#FF4500'],
	'tomato' => ['qcode' => 'tomato', 'cn' => '西红柿色', 'code' => '#FF6347'],
	'coral' => ['qcode' => 'coral', 'cn' => '珊瑚色', 'code' => '#FF7F50'],
	'darkorange' => ['qcode' => '', 'cn' => '暗桔黄色', 'code' => '#FF8C00'],
	'orange' => ['qcode' => 'orange', 'cn' => '橙色', 'code' => '#FFA500'],
	'chocolate' => ['qcode' => 'chocolate', 'cn' => '巧可力色 ', 'code' => '#D2691E'],
	'darkgoldenrod' => ['qcode' => 'darkgoldenrod', 'cn' => '暗金黄色', 'code' => '#B8860B'],
	'goldenrod' => ['qcode' => 'goldenrod', 'cn' => '金麒麟色', 'code' => '#DAA520'],
	'gold' => ['qcode' => 'gold', 'cn' => '金色', 'code' => '#FFD700'],
	'yellow' => ['qcode' => 'yellow', 'cn' => '黄色', 'code' => '#FFFF00'],
	'palegoldenrod' => ['qcode' => '', 'cn' => '苍麒麟色', 'code' => '#EEE8AA'],
	'khaki' => ['qcode' => 'khaki', 'cn' => '黄褐色', 'code' => '#F0E68C'],
	'darkkhaki' => ['qcode' => '', 'cn' => '暗黄褐色', 'code' => '#BDB76B'],
	'darkolivegreen' => ['qcode' => 'darkolivegreen', 'cn' => '暗橄榄绿', 'code' => '#556B2F'],
	'olive' => ['qcode' => '', 'cn' => '橄榄色', 'code' => '#808000'],
	'olivedrab' => ['qcode' => 'olivedrab', 'cn' => '深绿褐色', 'code' => '#6B8E23'],
	'darkgreen' => ['qcode' => 'darkgreen', 'cn' => '暗绿色', 'code' => '#006400'],
	'green' => ['qcode' => 'green', 'cn' => '绿色', 'code' => '#008000'],
	'forestgreen' => ['qcode' => 'forestgreen', 'cn' => '森林绿 ', 'code' => '#228B22'],
	'yellowgreen' => ['qcode' => 'yellowgreen', 'cn' => '黄绿色', 'code' => '#9ACD32'],
	'greenyellow' => ['qcode' => 'greenyellow', 'cn' => '黄绿色', 'code' => '#ADFF2F'],
	'lawngreen' => ['qcode' => 'lawngreen', 'cn' => '草绿色', 'code' => '#7CFC00'],
	'chartreuse' => ['qcode' => 'chartreuse', 'cn' => '黄绿色', 'code' => '#7FFF00'],
	'lime' => ['qcode' => 'lime', 'cn' => '酸橙色', 'code' => '#00FF00'],
	'limegreen' => ['qcode' => 'limegreen', 'cn' => '橙绿以', 'code' => '#32CD32'],
	'palegreen' => ['qcode' => 'palegreen', 'cn' => '苍绿色 ', 'code' => '#98FB98'],
	'lightgreen' => ['qcode' => 'lightgreen', 'cn' => '亮绿色 ', 'code' => '#90EE90'],
	'mediumspringgreen' => ['qcode' => 'mediumspringgreen', 'cn' => '间春绿色', 'code' => '#00FA9A'],
	'springgreen' => ['qcode' => 'springgreen', 'cn' => '春绿色', 'code' => '#00FF7F'],
	'turquoise' => ['qcode' => 'turquoise', 'cn' => '青绿色', 'code' => '#40E0D0'],
	'paleturquoise' => ['qcode' => 'paleturquoise', 'cn' => '苍宝石绿 ', 'code' => '#AFEEEE'],
	'powderblue' => ['qcode' => 'powderblue', 'cn' => '粉蓝色', 'code' => '#B0E0E6'],
	'lightblue' => ['qcode' => 'lightblue', 'cn' => '亮蓝色', 'code' => '#ADD8E6'],
	'lightsteelblue' => ['qcode' => 'lightsteelblue', 'cn' => '亮钢兰色', 'code' => '#B0C4DE'],
	'aquamarine' => ['qcode' => 'aquamarine', 'cn' => '碧绿色', 'code' => '#7FFFD4'],
	'cyan' => ['qcode' => 'cyan', 'cn' => '青色', 'code' => '#00FFFF'],
	'lightseagreen' => ['qcode' => 'lightseagreen', 'cn' => '亮海蓝色', 'code' => '#20B2AA'],
	'darkturquoise' => ['qcode' => 'darkturquoise', 'cn' => '暗宝石绿', 'code' => '#00CED1'],
	'mediumturquoise' => ['qcode' => 'mediumturquoise', 'cn' => '间绿宝石', 'code' => '#48D1CC'],
	'deepskyblue' => ['qcode' => 'deepskyblue', 'cn' => '深天蓝色', 'code' => '#00BFFF'],
	'lightskyblue' => ['qcode' => 'lightskyblue', 'cn' => '亮天蓝色', 'code' => '#87CEFA'],
	'skyblue' => ['qcode' => 'skyblue', 'cn' => '天蓝色', 'code' => '#87CEEB'],
	'mediumaquamarine' => ['qcode' => 'mediumaquamarine', 'cn' => '间绿色', 'code' => '#66CDAA'],
	'mediumseagreen' => ['qcode' => 'mediumseagreen', 'cn' => '间海蓝', 'code' => '#3CB371'],
	'seagreen' => ['qcode' => 'seagreen', 'cn' => '海绿色', 'code' => '#2E8B57'],
	'darkseagreen' => ['qcode' => 'darkseagreen', 'cn' => '暗海兰色', 'code' => '#8FBC8F'],
	'darkslategray' => ['qcode' => 'darkslategray', 'cn' => '墨绿色 ', 'code' => '#2F4F4F'],
	'teal' => ['qcode' => '', 'cn' => '水鸭色', 'code' => '#008080'],
	'darkcyan' => ['qcode' => 'darkcyan', 'cn' => '暗青色', 'code' => '#008B8B'],
	'cadetblue' => ['qcode' => 'cadetblue', 'cn' => '军兰色', 'code' => '#5F9EA0'],
	'dodgerblue' => ['qcode' => 'dodgerblue', 'cn' => '闪兰色', 'code' => '#1E90FF'],
	'royalblue' => ['qcode' => 'royalblue', 'cn' => '皇家蓝', 'code' => '#4169E1'],
	'steelblue' => ['qcode' => 'steelblue', 'cn' => '钢兰色', 'code' => '#4682B4'],
	'cornflowerblue' => ['qcode' => '', 'cn' => '菊兰色', 'code' => '#6495ED'],
	'blue' => ['qcode' => 'blue', 'cn' => '蓝色 ', 'code' => '#0000FF'],
	'mediumblue' => ['qcode' => 'mediumblue', 'cn' => '间兰色', 'code' => '#0000CD'],
	'navy' => ['qcode' => 'navy', 'cn' => '海军色', 'code' => '#000080'],
	'darkblue' => ['qcode' => 'darkblue', 'cn' => '暗蓝色', 'code' => '#00008B'],
	'midnightblue' => ['qcode' => 'midnightblue', 'cn' => '中灰兰色', 'code' => '#191970'],
	'darkslateblue' => ['qcode' => 'darkslateblue', 'cn' => '暗灰蓝色', 'code' => '#483D8B'],
	'mediumslateblue' => ['qcode' => 'mediumslateblue', 'cn' => '间暗蓝色', 'code' => '#7B68EE'],
	'mediumpurple' => ['qcode' => '', 'cn' => '间紫色', 'code' => '#9370DB'],
	'slateblue' => ['qcode' => '', 'cn' => '石蓝色', 'code' => '#6A5ACD'],
	'indigo' => ['qcode' => '', 'cn' => '靛青色', 'code' => '#4B0082'],
	'darkviolet' => ['qcode' => 'darkviolet', 'cn' => '暗紫罗兰色', 'code' => '#9400D3'],
	'darkorchid' => ['qcode' => 'darkorchid', 'cn' => '暗紫色', 'code' => '#9932CC'],
	'blueviolet' => ['qcode' => 'blueviolet', 'cn' => '紫罗兰色', 'code' => '#8A2BE2'],
	'mediumorchid' => ['qcode' => 'mediumorchid', 'cn' => '间紫色', 'code' => '#BA55D3'],
	'orchid' => ['qcode' => 'orchid', 'cn' => '淡紫色', 'code' => '#DA70D6'],
	'violet' => ['qcode' => 'violet', 'cn' => '紫罗兰色', 'code' => '#EE82EE'],
	'plum' => ['qcode' => 'plum', 'cn' => '洋李色', 'code' => '#DDA0DD'],
	'thistle' => ['qcode' => 'thistle', 'cn' => '蓟色', 'code' => '#D8BFD8'],
	'purple' => ['qcode' => 'purple', 'cn' => '紫色', 'code' => '#800080'],
	'darkmagenta' => ['qcode' => 'darkmagenta', 'cn' => '暗洋红 ', 'code' => '#8B008B'],
	'mediumvioletred' => ['qcode' => 'mediumvioletred', 'cn' => '间紫罗兰色', 'code' => '#C71585'],
	'deeppink' => ['qcode' => 'deeppink', 'cn' => '深粉红色', 'code' => '#FF1493'],
	'magenta' => ['qcode' => 'magenta', 'cn' => '红紫色', 'code' => '#FF00FF'],
	'hotpink' => ['qcode' => 'hotpink', 'cn' => '热粉红色', 'code' => '#FF69B4'],
	'lightcoral' => ['qcode' => 'lightcoral', 'cn' => '亮珊瑚色', 'code' => '#F08080'],
	'lightpink' => ['qcode' => 'lightpink', 'cn' => '亮粉红色', 'code' => '#FFB6C1'],
	'pink' => ['qcode' => 'pink', 'cn' => '粉红色', 'code' => '#FFC0CB'],
	'rosybrown' => ['qcode' => 'rosybrown', 'cn' => '褐玫瑰红', 'code' => '#BC8F8F'],
	'palevioletred' => ['qcode' => 'palevioletred', 'cn' => '苍紫罗兰色', 'code' => '#DB7093'],
	'indianred' => ['qcode' => 'indianred', 'cn' => '印第安红', 'code' => '#CD5C5C'],
	'salmon' => ['qcode' => 'salmon', 'cn' => '鲜肉色', 'code' => '#FA8072'],
	'darksalmon' => ['qcode' => 'darksalmon', 'cn' => '暗肉色', 'code' => '#E9967A'],
	'lightsalmon' => ['qcode' => 'lightsalmon', 'cn' => '亮肉色', 'code' => '#FFA07A'],
	'sandybrown' => ['qcode' => 'sandybrown', 'cn' => '沙褐色', 'code' => '#F4A460'],
	'peru' => ['qcode' => 'peru', 'cn' => '秘鲁色', 'code' => '#CD853F'],
	'sienna' => ['qcode' => 'sienna', 'cn' => '赭色', 'code' => '#A0522D'],
	'saddlebrown' => ['qcode' => 'saddlebrown', 'cn' => '重褐色 ', 'code' => '#8B4513'],
	'burlywood' => ['qcode' => 'burlywood', 'cn' => '实木色', 'code' => '#DEB887'],
	'tan' => ['qcode' => 'tan', 'cn' => '茶色', 'code' => '#D2B48C'],
	'peachpuff' => ['qcode' => 'peachpuff', 'cn' => '桃色', 'code' => '#FFDAB9'],
	'bisque' => ['qcode' => 'bisque', 'cn' => '桔黄色 ', 'code' => '#FFE4C4'],
	'mistyrose' => ['qcode' => 'mistyrose', 'cn' => '浅玫瑰色', 'code' => '#FFE4E1'],
	'papayawhip' => ['qcode' => 'papayawhip', 'cn' => '番木色', 'code' => '#FFEFD5'],
	'blanchedalmond' => ['qcode' => 'blanchedalmond', 'cn' => '白杏色', 'code' => '#FFEBCD'],
	'antiquewhite' => ['qcode' => '', 'cn' => '古董白 ', 'code' => '#FAEBD7'],
	'moccasin' => ['qcode' => 'moccasin', 'cn' => '鹿皮色', 'code' => '#FFE4B5'],
	'navajowhite' => ['qcode' => 'navajowhite', 'cn' => '纳瓦白', 'code' => '#FFDEAD'],
	'wheat' => ['qcode' => 'wheat', 'cn' => '浅黄色', 'code' => '#F5DEB3'],
	'lemonchiffon' => ['qcode' => 'lemonchiffon', 'cn' => '柠檬绸色', 'code' => '#FFFACD'],
	'lightgoldenrodyellow' => ['qcode' => '', 'cn' => '亮金黄色 ', 'code' => '#FAFAD2'],
	'cornsilk' => ['qcode' => 'cornsilk', 'cn' => '米绸色 ', 'code' => '#FFF8DC'],
	'lightyellow' => ['qcode' => 'lightyellow', 'cn' => '亮黄色', 'code' => '#FFFFE0'],
	'oldlace' => ['qcode' => 'oldlace', 'cn' => '老花色', 'code' => '#FDF5E6'],
	'seashell' => ['qcode' => 'seashell', 'cn' => '海贝色', 'code' => '#FFF5EE'],
	'lavenderblush' => ['qcode' => 'lavenderblush', 'cn' => '淡紫红', 'code' => '#FFF0F5'],
	'linen' => ['qcode' => '', 'cn' => '亚麻色', 'code' => '#FAF0E6'],
	'beige' => ['qcode' => 'beige', 'cn' => '米色', 'code' => '#F5F5DC'],
	'slategray' => ['qcode' => 'slategray', 'cn' => '灰石色', 'code' => '#708090'],
	'lightslategray' => ['qcode' => 'lightslategray', 'cn' => '亮蓝灰', 'code' => '#778899'],
	'dimgray' => ['qcode' => 'dimgray', 'cn' => '暗灰色', 'code' => '#696969'],
	'gray' => ['qcode' => 'gray', 'cn' => '灰色', 'code' => '#808080'],
	'darkgray' => ['qcode' => 'darkgray', 'cn' => '暗灰色', 'code' => '#A9A9A9'],
	'silver' => ['qcode' => 'silver', 'cn' => '银色', 'code' => '#C0C0C0'],
	'lightgrey' => ['qcode' => '', 'cn' => '亮灰色', 'code' => '#D3D3D3'],
	'gainsboro' => ['qcode' => 'gainsboro', 'cn' => '淡灰色', 'code' => '#DCDCDC'],
	'lavender' => ['qcode' => 'lavender', 'cn' => '淡紫色 ', 'code' => '#E6E6FA'],
	'lightcyan' => ['qcode' => 'lightcyan', 'cn' => '亮青色', 'code' => '#E0FFFF'],
	'aliceblue' => ['qcode' => 'aliceblue', 'cn' => '艾利斯兰 ', 'code' => '#F0F8FF'],
	'azure' => ['qcode' => 'azure', 'cn' => '天蓝色', 'code' => '#F0FFFF'],
	'honeydew' => ['qcode' => 'honeydew', 'cn' => '蜜色 ', 'code' => '#F0FFF0'],
	'whitesmoke' => ['qcode' => 'whitesmoke', 'cn' => '烟白色', 'code' => '#F5F5F5'],
	'mintcream' => ['qcode' => 'mintcream', 'cn' => '薄荷色', 'code' => '#F5FFFA'],
	'ghostwhite' => ['qcode' => '', 'cn' => '幽灵白', 'code' => '#F8F8FF'],
	'floralwhite' => ['qcode' => 'floralwhite', 'cn' => '花白色 ', 'code' => '#FFFAF0'],
	'snow' => ['qcode' => 'snow', 'cn' => '', 'code' => '#FFFAFA'],
	'ivory' => ['qcode' => 'ivory', 'cn' => '象牙色', 'code' => '#FFFFF0'],
	'white' => ['qcode' => '', 'cn' => '白色', 'code' => '#FFFFFF']
];
$this->assign('colors', $COLORS);
